### ISSUE TITLE
Error: @typescript/lib-dom@npm:@types/web isn't supported by any available resolver 

### ISSUE THREAD

**Issue by mikob** [microsoft/TypeScript-DOM-lib-generator#1183]
Tried the install steps with 

typescript: 4.5.0-dev.20211019

and yarn v3.0.2

➤ YN0001: │ Error: @typescript/lib-dom@npm:@types/web isn't supported by any available resolver
    at Xc.getResolverByDescriptor (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:294:5330)
    at Xc.bindDescriptor (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:294:4719)
    at p (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:303:6959)
    at async Promise.all (index 1)
    at async Fe.resolveEverything (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:303:8166)
    at async /home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:306:2135
    at async xe.startTimerPromise (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:275:3730)
    at async Fe.install (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:306:2074)
    at async /home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:311:122
    at async Function.start (/home/mikob/workspace/lipsurf/chrome-extension/.yarn/releases/yarn-3.0.2.cjs:275:2287)

**Comment by mikob** [comment]
It's a yarn issue: https://github.com/yarnpkg/berry/issues/1621

**Comment by mnahkies** [comment]
Whilst it's a problem with `yarn`, just wanted to leave a note that you can workaround by adding this to your `package.json`:

```
  "resolutions": {
    "@typescript/lib-dom": "npm:@types/web@*",
  }
```
