### ISSUE TITLE
Ping @saschanaz whenever `Update core dependencies` action fails

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1282]
Something should ping me since I'm not the owner.

**Comment by saschanaz** [comment]
Hi @saschanaz, kindly pinging you as the 'Update core dependencies' job failed today.

**Comment by saschanaz** [comment]
Hi @saschanaz, kindly pinging you as the 'Update core dependencies' job failed today.

**Comment by sandersn** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/11908769649/job/33184821427 shows that the error is "Unknown DOM type: GPUError":

```
Error: Unknown DOM type: GPUError
    at convertDomTypeToTsTypeSimple (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:322:[15](https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/11908769649/job/33184821427#step:9:16))
    at convertBaseType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:266:24)
    at convertDomTypeToTsTypeWorker (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:278:22)
    at convertDomTypeToTsType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:247:22)
    at Array.map (<anonymous>)
    at convertDomTypeToTsTypeWorker (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:280:14)
    at convertDomTypeToTsType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:247:22)
    at convertDomTypeToTsReturnType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:251:[22](https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/11908769649/job/33184821427#step:9:23))
    at emitSignature (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:682:28)
    at file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:692:47
```

**Comment by saschanaz** [comment]
No, the issue is that Safari did not add GPUError (they somehow hacked it with enum) and thus per the support data GPUError has no two impl supports, and therefore the library is freaking out with inconsistency. I fixed it locally (manually enabled GPUError for now) but I have to verify the huge WebGPU additions 😵‍💫

**Comment by Bashamega** [comment]
Hello:)
After a quick look at the actions it seems that I has failed because the npm login credentials are invalid.

**Comment by saschanaz** [comment]
Oops, that's https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/2480.
