### ISSUE TITLE
Update job is failing

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1743]
It started failing two weeks ago: https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/9413792073/job/25931301970

@jakebailey, any idea why?

**Comment by jakebailey** [comment]
Sorry, lost this in my inbox. The token probably expired or something; will look at it.

**Comment by jakebailey** [comment]
Ah, the workflow has always been wrong, it's just now failing in `onUpdateFailure` because the previous step is failing:

```
(node:1857) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
removedTypes.json has a redundant field av1 in {"av1":null,"contentHint":null,"hevc":null}
file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:318
        throw new Error("Unknown DOM type: " + objDomType);
              ^
Error: Unknown DOM type: RTCIceCandidatePair
    at convertDomTypeToTsTypeSimple (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:318:15)
    at convertBaseType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:262:24)
    at convertDomTypeToTsTypeWorker (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:274:22)
    at convertDomTypeToTsType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:243:22)
    at convertDomTypeToTsReturnType (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:247:22)
    at emitSignature (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:671:28)
    at file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:681:47
    at Array.forEach (<anonymous>)
    at emitSignatures (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:681:30)
    at emitMethod (file:///home/runner/work/TypeScript-DOM-lib-generator/TypeScript-DOM-lib-generator/lib/build/emitter.js:666:[9](https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/9666645838/job/26666635079#step:9:10))
Node.js v20.14.0
```

So there's something unknown about `RTCIceCandidatePair`.

The workflow step is missing a token, so that's its own issue.
